version: '3'

services:

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=dynamodb, ses, iam
      - LOCALSTACK_HOST=localstack:4566
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./localstack:/etc/localstack/init/ready.d:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"