package br.com.fiap.soat.pontos.dynamodb.entities;

import br.com.fiap.soat.pontos.entities.Ponto;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.time.LocalDate;

@DynamoDbBean
@DynamoDBTable(tableName = "Pontos")
public class PontoDynamoEntity {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "usuario")
    private String usuario;

    @DynamoDBAttribute(attributeName = "data")
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate data;

    @DynamoDbPartitionKey
    @DynamoDbAttribute("id")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDbAttribute("usuario")
    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    @DynamoDbAttribute("data")
    public LocalDate getData() {
        return data;
    }

    public void setData(LocalDate data) {
        this.data = data;
    }

    public static PontoDynamoEntity fromDomain(Ponto ponto) {
        PontoDynamoEntity dynamoEntity = new PontoDynamoEntity();

        dynamoEntity.setId(ponto.getId());
        dynamoEntity.setUsuario(ponto.getUsuario());
        dynamoEntity.setData(ponto.getData());

        return dynamoEntity;
    }

    public Ponto toDomain() {
        return new Ponto(
                id,
                usuario,
                data
        );
    }


}
