name: Build and test

on:
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  infrastructure:
    needs:
      - java-quality
    uses: soat1-grupo18/hackathon-reusable-github-workflows/.github/workflows/aws-terraform.yml@main
    with:
      aws-region: us-east-1
      terraform-directory-path: infrastructure
      terraform-version: 1.7.0
    secrets: inherit

  java-microservice:
    needs:
      - infrastructure
    uses: soat1-grupo18/hackathon-reusable-github-workflows/.github/workflows/aws-ecs-java-microservice.yml@main
    with:
      application-path: .
      aws-region: us-east-1
      container-name: ms-ponto
      container-port: "8080"
      ecs-cluster-name: fiap-hackathon
      ecr-repository-name: ms-ponto
      ecs-service-name: ms-ponto
      java-distribution: corretto
      java-version: "17"
    secrets: inherit
